#!/bin/bash

tmux new-session -s lopocs -n serve -d
tmux send-keys -t lopocs:serve 'cd ~/src/lopocs && workon lopocs && lopocs serve' C-m

tmux new-window -n cli
tmux send-keys -t lopocs:cli 'cd ~/src/lopocs && workon lopocs' C-m

tmux new-window -n psql
tmux send-keys -t lopocs:psql 'psql -d lopocs -U lopocs' C-m

tmux new-window -n edit
tmux send-keys -t lopocs:edit 'cd ~/src/lopocs && workon main' C-m

tmux select-window -t serve
tmux attach -t lopocs
