#!/bin/bash

tmux new-session -s love -n git -d
tmux send-keys -t love:git 'cd ~/src/1605_07_rennes1_wpsdeploy' C-m

tmux new-window -n edit
tmux send-keys -t love:edit 'cd ~/src/1605_07_rennes1_wpsdeploy && workon main' C-m

tmux new-window -n vagrant
tmux send-keys -t love:vagrant 'cd ~/src/1605_07_rennes1_wpsdeploy/vagrant && workon ansible' C-m

tmux select-window -t git
tmux attach -t love
