#!/bin/bash

HOST=$1
: ${HOST:="mk20"}

cd ~/src/mk20/mk-lab-heat-templates

tmux new-session -s mk20 -n console -d
tmux send-keys -t mk20:console 'workon mk20 && source openrc' C-m

tmux new-window -n cfg -t mk20
tmux send-keys -t mk20:cfg "ssh -t -D 9999 $HOST" C-m
tmux send-keys -t mk20:cfg 'sudo -E su -p -' C-m
tmux send-keys -t mk20:cfg 'cd /srv/salt/reclass' C-m
tmux send-keys -t mk20:cfg 'workon main' C-m

tmux new-window -n cfg-vim -t mk20
tmux send-keys -t mk20:cfg-vim "ssh -t $HOST" C-m
tmux send-keys -t mk20:cfg-vim 'sudo -E su -p -' C-m
tmux send-keys -t mk20:cfg-vim 'cd /usr/share/salt-formulas/env/_formulas' C-m
tmux send-keys -t mk20:cfg-vim 'workon main' C-m

tmux new-window -n mon -t mk20
tmux send-keys -t mk20:mon "ssh -t $HOST ssh mon" C-m

tmux new-window -n ctl01 -t mk20
tmux send-keys -t mk20:ctl01 "ssh -t $HOST sudo -E ssh ctl01" C-m

tmux new-window -n ctl02 -t mk20
tmux send-keys -t mk20:ctl02 "ssh -t $HOST sudo -E ssh ctl02" C-m

tmux new-window -n ctl03 -t mk20
tmux send-keys -t mk20:ctl03 "ssh -t $HOST sudo -E ssh ctl03" C-m

tmux select-window -t console
tmux attach -t mk20
