#!/bin/bash

tmux new-session -s stcgeom -n git -d
tmux send-keys -t stcgeom:git 'cd ~/src/1708_07_sncf_refonte_stc_geom' C-m

tmux new-window -n edit
tmux send-keys -t stcgeom:edit 'cd ~/src/1708_07_sncf_refonte_stc_geom && workon main' C-m

tmux new-window -n test
tmux send-keys -t stcgeom:test 'cd ~/src/1708_07_sncf_refonte_stc_geom && workon stc' C-m

tmux select-window -t edit
tmux attach -t stcgeom
